//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CartRoverEntities : DbContext
    {
        public CartRoverEntities()
            : base("name=CartRoverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ClientLocation> ClientLocations { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<OrderCR> OrderCRs { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderProcessLog> OrderProcessLogs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RefCategory> RefCategories { get; set; }
        public virtual DbSet<RefClientCategory> RefClientCategories { get; set; }
        public virtual DbSet<RefOrderType> RefOrderTypes { get; set; }
        public virtual DbSet<RefProductFamily> RefProductFamilies { get; set; }
        public virtual DbSet<RefSeason> RefSeasons { get; set; }
        public virtual DbSet<RefWarehouse> RefWarehouses { get; set; }
        public virtual DbSet<Sales_Report> Sales_Reports { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<OrderProcessForce> OrderProcessForces { get; set; }
    }
}
